apiVersion: v1
kind: Service
metadata:
  name: customerapi-mssql-service
spec:
  selector:
    app: customerapi-mssql
  ports:
    - protocol: TCP
      port: 1433
      targetPort: 1433
  type: ClusterIP