apiVersion: apps/v1
kind: Deployment
metadata:
  name: customerapi-deployment
spec:
  selector:
    matchLabels:
      app: customerapi
  template:
    metadata:
      labels:
        app: customerapi
    spec:
      containers:
      - name: customerapi-container
        image: acrcustomerapi.azurecr.io/customerapi
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        env:
          - name: DBServer
            value: "kfmicrosvc.database.windows.net"
          - name: Database
            value: "customers"
          - name: DBUser
            value: "sqladmin"
          - name: DBPassword
            value: "Pa55w0rd2020"
        ports:
        - containerPort: 80
