apiVersion: apps/v1
kind: Deployment
metadata:
  name: customerapi-deployment
spec:
  selector:
    matchLabels:
      app: customerapi
  template:
    metadata:
      labels:
        app: customerapi
    spec:
      containers:
      - name: customerapi-container
        image: acrcustomerapi.azurecr.io/customerapi
        env:
        - name: DBServer
          value: '$(DBServer)'
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: customerapi-service
spec:
  selector:
    app: customerapi
  ports:
  - port: 8080
    targetPort: 80
  type: LoadBalancer