version: '3'
services: 
  ms-sql-server:
    image: "mcr.microsoft.com/mssql/server:2017-latest-ubuntu"
    environment: 
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "Pa55w0rd2020"
      MSSQL_PID: Express
    ports:
      - "1433:1433"
  customer-api:
    build: .
    environment: 
      DBServer: "ms-sql-server"
    ports:
      - "7991:80"